server/connect/connectApiExpress.js, server/providers/akoya.ts, server/providers/index.ts, server/serviceClients/searchClient/ucp.js
fix the issue that The auth url format used some restricted characters that was causing error from akoya.
=> Fix akoya handling

.husky/pre-commit, .prettierrc.js, cypress.config.ts, jest.config.js, package-lock.json, package.json, server/__tests__/index.test.js
This PR adds husky pre-commit hook to run Linting prior to allowing a commit.
=> Add precommit lint checking

server/providers/mx.ts
Example app Auth mode wasn't triggering the verification job.
=> fix auth not triggering verification for mx

server/connect/connectApiExpress.js
Fixing stubbed out endpoint `unthrottled_aggregate`
=> Fix Agg in Oauth

Dockerfile, package-lock.json, package.json, ui/.dockerignore, ui/Dockerfile, ui/package.json
Updates docker file to only install production deps. Tested with `docker-compose up`
=> Update to only run with prod deps for docker image

server/connect/connectApiExpress.js, server/providers/mx.ts, server/serviceClients/mxClient/api.ts, shared/contract.ts
Copying server code updates from https://github.com/Universal-Connect-Project/universal-connect-widget to keep parity.
=> Copy updates over from other repo.

docker-compose.yaml, package.json, ui/package-lock.json, ui/package.json
Updates to the version of the widget that has the fix for images not showing up.
=> Update to v0.0.7-beta of npm package

.env.example, .github/workflows/docker-publish.yml, .github/workflows/e2e-tests.yml, .github/workflows/setup-env.yml, .github/workflows/unit-tests.yml, Dockerfile, README.md, docker-compose.yaml, package.json, server/config.ts, server/server.js, ui/Dockerfile, ui/README.md, ui/package-lock.json, ui/package.json
This PR adds a GitHub Action workflow that auto builds and publishes the docker images to Dockerhub. 
_Note, most of the commits to this PR were due to the difficult nature of debugging GH actions. I'm not aware of a way to test these offline, and as such, I had to commit changes to see if they worked. I will squash and merge so as not to muddy the history with my tomfoolery._
=> GH Actions for publishing to docker hub

.github/workflows/docker-publish.yml
The check is using the old image names.
=> Fix docker image check

MONOREPO.md
The example commands for interacting with workspaces was incorrect.
=> Fix workspace example commands

apps/server/src/shared/contract.ts
Testing coming soon in a new PR
=> Fix oauth not getting status right

apps/server/cypress/e2e/fuzzySearch.cy.ts, apps/server/src/utils/ElasticSearchClient.test.ts, apps/server/src/utils/ElasticSearchClient.ts
Fixing search to not break tests
=> getting search results a little better

apps/server/package.json, docker-compose.yml
This will make it so elasticsearch doesn't have to reinitialize every time the container restarts.
=> Use docker volume to save elasticsearch index

apps/server/cachedDefaults/preferences.example.json, apps/server/cachedDefaults/testData/testPreferences.json, apps/server/src/shared/preferences.ts, apps/server/src/utils/institutionResolver.test.ts, apps/server/src/utils/institutionResolver.ts
https://universalconnect.atlassian.net/browse/UCP-158
Adding supportedProviders in preferences and fix routing to use it.
=> Add supportedProviders to preference and route by it. UCP-158

.github/workflows/e2e-playwright.yml, apps/server/.env.example, apps/server/playwright/mx.playwright.ts, apps/server/src/connect/connectApiExpress.js, apps/server/src/infra/http/oauth.html, apps/server/src/providers/mx.test.ts, apps/server/src/providers/mx.ts
Issue: https://universalconnect.atlassian.net/browse/UCP-152
Added a oauth landing page.
=> Create simple oauth landing page and redirect to it

apps/server/src/providers/finicity.test.ts, apps/server/src/test/handlers.ts
Issue: https://universalconnect.atlassian.net/browse/UCP-153
Fixes MSW message in the console when tests are run.
=> Fix MSW message in Finicity tests UCP-153

DOCKER.md, README.md
Clarify some things, as well as add some additional information.
=> Updates to readme

apps/server/src/adapters/index.ts, apps/server/src/connect/connectApi.test.ts, apps/server/src/connect/institutionEndpoints.test.ts, apps/server/src/connect/institutionEndpoints.ts, apps/server/src/services/ElasticSearchClient.ts, apps/server/src/services/institutionResolver.test.ts, apps/server/src/services/institutionResolver.ts
Issue: https://universalconnect.atlassian.net/browse/UCP-163
Resolver checks jobtype to see if provider supports it.
=> Consider JobType when resolving an institution

apps/server/src/connect/dataEndpoints.ts, apps/server/src/connect/userEndpoints.test.ts, apps/server/src/connect/userEndpoints.ts, apps/server/src/utils/index.ts, apps/server/src/utils/validators.ts
Issue: https://universalconnect.atlassian.net/browse/UCP-232
Adds some validation to the delete user endpoint
=> Add param validation to delete user endpoint

apps/server/cypress/e2e/suite1/search.cy.ts, apps/server/src/connect/connectApi.ts, apps/server/src/connect/institutionEndpoints.test.ts, apps/server/src/connect/institutionEndpoints.ts, apps/server/src/services/ElasticSearchClient.test.ts, apps/server/src/services/ElasticSearchClient.ts, apps/server/src/shared/contract.ts, apps/server/src/test/testData/institution.ts
Issue: https://universalconnect.atlassian.net/browse/UCP-237
=> Allow search by routing number

PREFERENCES.md, apps/server/cachedDefaults/testData/alternateTestPreferences.json, apps/server/cachedDefaults/testData/testPreferences.json, apps/server/cypress/e2e/suite1/queryParameters.cy.ts, apps/server/src/connect/connectApi.ts, apps/server/src/services/ElasticSearchClient.test.ts, apps/server/src/services/ElasticSearchClient.ts, apps/server/src/services/institutionSyncer.test.ts, apps/server/src/shared/contract.ts, apps/server/src/shared/providers.test.ts, apps/server/src/test/testData/institution.ts
Updates ucp_ids following this MR https://github.com/Universal-Connect-Project/ucp-hosted-app/pull/56
=> change ucp_id to id and update institution ids

apps/ui/package.json, package-lock.json
Updates package to include this change in the package ui - https://github.com/Universal-Connect-Project/universal-connect-widget-new/pull/21
=> Updates ui package for logo change

ADAPTERS.md, NPM.md
Added NPM.md to outline how publishing to NPM works.
=> New NPM publishing docs

apps/server/src/adapterSetup.ts
=> Clean up API URLs

CHANGELOG.md, apps/server/cypress/e2e/syncingSuite/institutionSyncing.cy.ts, apps/server/env/sharedProduction.env, apps/server/env/sharedStaging.env, package-lock.json, package.json, packages/sophtron-adapter/src/adapter.test.ts, packages/sophtron-adapter/src/adapter.ts
This change fixes an incomplete implementation in sophtron adapter that it couldn't handle multiple security question
=> handle multiple security question in sophtron adapter
